### ISSUE TITLE
Maximising the probability of output == target given data -- P(y=T|x)

### ISSUE THREAD

**Issue by act65** [garibaldu/comp421#6]
This still feels a little weird. 
The probability of y=T given x makes me think that we are sampling y given x, but that is generally not the case as we have/use deterministic algorithms??
For example in a neural net, given some x, and some parameters W, the answer should always be the same y?!? So in which sense can we maximise the probability that y = T? as either y = T or it doesnt...?

**Comment by garibaldu** [comment]
Yes our neural network (or other learner) is producing outputs deterministically, and these numbers are dependent on the input vector x. Suppose this number, given some x, is 0.7 but the target is 1. We need some way to compare the two, and for the comparison to drive learning, ie. we need some measure of "goodness" (or "badness") for the learning process to maximize (or minimize).
Question is: what's a sensible measure to use in any given situation?
ONE WAY to approach this is to instead think of the output of learner as encoding a _distribution_ of some sort, because then we can write down the _likelihood_, that is, the probability that a sample from this distribution would match the target value.
For regression (real-valued outputs), a natural distribution to use is the Gaussian: this immediately leads to the the sum-of-squares badness measure. A corollary is that this measure might make particularly good sense in cases where we actually do believe the world is adding Gaussian noise to the targets we're seeing, because learning the mean of the Gaussian suggests we're learning something useful about the real world.
But if the output being 1 (or 0) is really meaning that it's "class 1, vs class 0" (classification, not regression), then that's a silly score to use. Instead, we can think of the 0.7 being emitted by the learner as representing a Bernoulli distribution (a "bent coin"), and immediately write down the probability that sampling from that would give a 1. Hence we get a gradient to train the network that only outputs floats despite the fact that the targets aren't floats. [So you can in fact bring a knife to a gunfight, as long as you're prepared to interpret the knife as a distribution, ha ha. ]

**Comment by garibaldu** [comment]
Wonder if I can put latex into this $y=\exp^{\log{y}} $
